### ISSUE TITLE
Good stuff!

### ISSUE THREAD

**Issue by mcw0** [zb3/tvt-firmware-decryptor#1]
Thanks, this made my day today!

Just FYI, this still working in late 2023. Not only for TVT, but also for their OEM.

Thanks for your work, much appreciated!

**Comment by zb3** [comment]
Thanks for reaching out, good to hear that :D 
This is quite surprising given they didn't use RSA properly so in theory it's possible to repack the firmware, because the private exponent is available

**Comment by p2p-sys** [comment]
@zb3 @mcw0 Is it possible to unpack 2023 DVR firmware from dahua ?

> Exception: Unrecognized file format!

**Comment by zb3** [comment]
@p2p-sys Unfortunately no, because this is focused on TVT firmware. Dahua is a separate vendor so you'd need a different tool.
